using System;

namespace EsavApi.Validador.NEAR.BE.NotaCredito
{
    public class beNotaCreditoImpuesto
    {
        public int accion { get; set; }
        public string IdEmisor { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public string idIGV { get; set; }
        public string codeIGV { get; set; }
        public string nameIGV { get; set; }
        public string tipoIGV { get; set; }
        public decimal tIgv { get; set; }
        public string idISC { get; set; }
        public string codeISC { get; set; }
        public string nameISC { get; set; }
        public string tipoISC { get; set; }
        public string idOTH { get; set; }
        public string codeOTH { get; set; }
        public string nameOTH { get; set; }
        public string tipoOTH { get; set; }
        public string idICBPER { get; set; }
        public string codeICBPER { get; set; }
        public string nameICBPER { get; set; }
        public string tipoICBPER { get; set; }
        public string codigotGravada { get; set; }
        public string nameGravada { get; set; }
        public string tipoGravada { get; set; }
        public string codigotInafecta { get; set; }
        public string nameInafecta { get; set; }
        public string tipoInafecta { get; set; }
        public string idINF { get; set; }
        public string codeINF { get; set; }
        public string nameINF { get; set; }
        public string codigotExonerada { get; set; }
        public string nameExonerada { get; set; }
        public string tipoExonerada { get; set; }
        public string idEXO { get; set; }
        public string codeEXO { get; set; }
        public string nameEXO { get; set; }
        public string codigotGratuita { get; set; }
        public string nameGratuita { get; set; }
        public string tipoGratuita { get; set; }
        public string idGRT { get; set; }
        public string codeGRT { get; set; }
        public string nameGRT { get; set; }
        public string codigotExportacion { get; set; }
        public string nameExportacion { get; set; }
        public string tipoExportacion { get; set; }
        public string idEXP { get; set; }
        public string codeEXP { get; set; }
        public string nameEXP { get; set; }
        public string codigotDescuento { get; set; }
        public string nameDescuento { get; set; }
        public string tipoDescuento { get; set; }
        public string codigotDescuentoGlobal { get; set; }
        public string codigoMotivotDescuentoGlobal { get; set; }
        public decimal pctDescuentoGlobal { get; set; }
        public decimal tDescuentoGlobalBaseAmount { get; set; }
        public string codigotOtrosCargosGlobal { get; set; }
        public string codigoMotivotOtrosCargosGlobal { get; set; }
        public decimal pctOtrosCargos { get; set; }
        public decimal tOtrosCargosGlobalBaseAmount { get; set; }
        public decimal tOtrosCargosGlobal { get; set; }
        public string codigoMotivoRetencion { get; set; }
        public decimal pctRetencion { get; set; }
        public decimal tRetencionBaseAmount { get; set; }
        public decimal tRetencion { get; set; }
        public string codigotOtrosCargosRecargo { get; set; }
        public string codigoMotivotOtrosCargosRecargo { get; set; }
        public decimal pctOtrosCargoRecargo { get; set; }
        public decimal tOtrosCargosRecargoBaseAmount { get; set; }
        public string monedaPercepcion { get; set; }
        public string regimenPercepcion { get; set; }
        public string motivoPercepcion { get; set; }
        public string codigotImportePercepcion { get; set; }
        public string nameImportePercepcion { get; set; }
        public string tipoPercepcion { get; set; }
        public decimal tBaseImponible { get; set; }
        public decimal tValorVenta { get; set; }
        public decimal tSubtotal { get; set; }
        public decimal tDescuento { get; set; }
        public string Amount_CurrencyID { get; set; }
        public string Ca22_Id { get; set; }
        public string Ca53_Id { get; set; }
        public decimal tIsc { get; set; }
        public decimal tExonerada { get; set; }
        public decimal tGratuita { get; set; }
        public decimal tGravada { get; set; }
        public decimal tInafecta { get; set; }
        public decimal tOtrosTributos { get; set; }
        public decimal tIcbper { get; set; }
        public decimal tOtrosCargos { get; set; }
        public decimal tExportacion { get; set; }
        public decimal tDescuentoGlobal { get; set; }

        public decimal tOtrosCargosRecargo { get; set; }
        public decimal tImporteAnticipado { get; set; }
        public decimal tImporteTotal { get; set; }
        public decimal tImporteTotalReferencia { get; set; }
        public decimal tImportePercepcion { get; set; }
        public decimal tImporteCobrar { get; set; }
        public decimal tImporteTotalPercepcion { get; set; }
        public decimal ValortDescuento { get; set; }
        public decimal BasetDescuento { get; set; }
        public string AnticipoAllowanceChargeReasonCode { get; set; }
        public decimal tAnticipoDescuentoAmount { get; set; }
        public decimal tAnticipoDescuentoMultiplierFactorNumeric { get; set; }
        public decimal tAnticipoDescuentoBaseAmount { get; set; }
        public decimal pctOtrosCargosGlobales { get; set; }
        public decimal tPercepcionBaseAmount { get; set; }
        public decimal pctPercepcionGlobales { get; set; }
        public decimal tOTHBaseAmount { get; set; }

        public string usuario { get; set; }
        public string Fecha { get; set; }
        public string Ip { get; set; }
        public int Registro { get; set; }
        public bool Estado { get; set; }

        public string Ca02_TaxAmount { get; set; }
        public decimal TaxAmount_TaxSubTotal { get; set; }
        public string Ca02_TaxAmount_TaxSubTotal { get; set; }
        public string Ca05_TaxAmount_TaxSubTotal { get; set; }
    }
}
